[project]
name = "arm-kinematics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "pygame>=2.6.1",
    "scipy>=1.15.3",
]
